appname = casdoor
httpport = 8000
copyrequestbody = true
driverName = postgres
dataSourceName = host=172.16.0.7 port=15000 user=casdoor password=casdoorpw. dbname=casdoor sslmode=disable
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
socks5Proxy = "127.0.0.1:10808"
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
isUsernameLowered = false
origin =
originFrontend =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
enableErrorMask = false
enableGzip = true
inactiveTimeoutMinutes =
ldapServerPort = 389
ldapsCertId = ""
ldapsServerPort = 636
radiusServerPort = 1812
radiusDefaultOrganization = "built-in"
radiusSecret = "secret"
quota = {
  #$#%#$#placeholder03434#$#%#$#: -1, #$#%#$#placeholder13434#$#%#$#: -1, #$#%#$#placeholder23434#$#%#$#: -1, #$#%#$#placeholder33434#$#%#$#: -
}
logConfig = {
  #$#%#$#placeholder03434#$#%#$#:#$#%#$#placeholder13434#$#%#$#, #$#%#$#placeholder23434#$#%#$#: #$#%#$#placeholder33434#$#%#$#, #$#%#$#placeholder43434#$#%#$#:99999, #$#%#$#placeholder53434#$#%#$#:#$#%#$#placeholder63434#$#%#$